# interval to check on
interval: 120m

# averge memory usage across cells at which to scale up
threshold: 65
# number of instances to scale up by
increment: 2

# minimum number of instances (don't scale below this number of cells)
minimum_instance_count: 3

# the full URL to the PCF operations manager for the foundation you want to harden
oopsman_domain_or_ip_address: CHANGEME

# username and password to use to connect to the PCF Operations Manager, ideally put these in secrets management
opsman_admin_username:  CHANGEME            # sensitive
opsman_admin_password: CHANGEME         # sensitive

# if you're using a client id/secret instead of username password, set these
opsman_client_id: CHANGEME        # sensitive
opsman_client_secret: CHANGEME    # sensitive

# old-style token to access the Pivotal Network to access the PCF pipelines, ideally put this in secrets management
pivnet_token: CHANGEME            # sensitive
pcf_pipelines_version: v0.23.5    # change if you're using a different version, YMMV

# Service account credfile json with access to get GCP compute instance details
opsman_gcp_project: CHANGEME
opsman_gcp_credfile_contents: CHANGEME

# Repository with the autoscale task - for example: https://github.com/crdant/diego-autoscale-pipeline.git
diego-autoscale-pipeline: CHANGEME
