jobs:
- name: autoscale-cells
  plan:
  - aggregate:
    - get: schedule
      trigger: true
    - do:
      - get: pcf-pipelines-tarball
      - task: unpack-tarball
        config:
          image_resource:
            source:
              repository: pcfnorm/rootfs
              tag: v0.2.7
            type: docker-image
          inputs:
          - name: pcf-pipelines-tarball
          outputs:
          - name: pcf-pipelines
          platform: linux
          run:
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
            path: bash
    - get: scale-pcf
  - task: wait-opsman-clear
    file: pcf-pipelines/tasks/wait-opsman-clear/task.yml
    params:
      OPSMAN_CLIENT_ID: ((opsman_client_id))
      OPSMAN_CLIENT_SECRET: ((opsman_client_secret))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
  - task: scale-cells
    file: scale-pcf/tasks/scale-cells/task.yml
    params:
      opsman_target: https://((opsman_domain_or_ip_address))
      opsman_user: ((opsman_admin_username))
      opsman_password: ((opsman_admin_password))
      cf_api_uri: ((cf_api_uri))
      cf_user: ((cf_user))
      cf_password: ((cf_password))
      threshold: ((threshold))
      increment: ((increment))
      minimum_instance_count: ((minimum_instance_count))
      gcp_project: ((opsman_gcp_project))
      gcp_credfile_contents: ((opsman_gcp_credfile_contents))
      foundation_name: ((foundation_name))
      webhook: ((teams_webhook_url))
    on_failure:
      <<: *failure_notification
    on_success:
      try:
        put: instance-status
        params:
          file: status/autoscale-instances.json
          predefined_acl: projectPrivate
          content_type: application/json
- name: apply-changes
  plan:
  - aggregate:
    - get: instance-status
      passed: [ autoscale-cells ]
      trigger: true
    - do:
      - get: pcf-pipelines-tarball
      - task: unpack-tarball
        config:
          image_resource:
            source:
              repository: pcfnorm/rootfs
              tag: v0.2.7
            type: docker-image
          inputs:
          - name: pcf-pipelines-tarball
          outputs:
          - name: pcf-pipelines
          platform: linux
          run:
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
            path: bash
  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_CLIENT_ID: ((opsman_client_id))
      OPSMAN_CLIENT_SECRET: ((opsman_client_secret))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_domain_or_ip_address))
    on_failure:
      <<: *failure_notification

resources:
- name: schedule
  type: time
  source:
    interval: ((interval))
    start: "12:00 AM"
    stop: "11:59 PM"
    location: America/Los_Angeles
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]
- name: scale-pcf
  type: git
  source:
    uri: ((diego-autoscale-pipeline))
- name: pcf-pipelines-tarball
  source:
    api_token: ((pivnet_token))
    product_slug: pcf-automation
    product_version: ((pcf_pipelines_version))
  type: pivnet
- name: instance-status
  type: gcs-resource
  source:
    bucket: ((gcs_autoscale_bucket_name))
    json_key: ((gcp_metadata_credfile_contents))
    versioned_file: ((opsman_domain_or_ip_address))/autoscale-instances.json
- name: teams-notification
  type: teams-notification
  source:
    url: ((teams_webhook_url))

resource_types:
- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: docker-image
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource
- name: teams-notification
  type: docker-image
  source:
    repository: richardg0510/teams-notification-resource
    tag: latest

failure_notification: &failure_notification
  put: teams-notification
  params:
    message: |
      "{
        \"@type\": \"MessageCard\",
        \"@context\": \"http://schema.org/extensions\",
        \"summary\": \"Diego Autoscale Pipeline Failure\",
        \"themeColor\": \"FF0000\",
        \"title\": \"Diego Autoscale Pipeline Failure\",
        \"sections\": [
          {
            \"text\": \"The Diego Autoscale pipeline has failed at the $BUILD_PIPELINE_NAME/$BUILD_JOB_NAME job.\",
            \"facts\": [
              { \"name\": \"Team:\", \"value\": \"$BUILD_TEAM_NAME\" },
              { \"name\": \"Pipeline Name:\", \"value\": \"$BUILD_PIPELINE_NAME\" },
              { \"name\": \"Job Name:\", \"value\": \"$BUILD_JOB_NAME\" },
              { \"name\": \"Build:\", \"value\": \"$BUILD_NAME\" },
              { \"name\": \"Link:\", \"value\": \"[$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME]($ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)\" }
            ]
          },
          {
            \"activitySubtitle\": \"Diego Autoscale Pipeline Failure.\"
          }
        ]
      }"
